# Generated by Django 5.0.2 on 2024-03-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='content',
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
