# Generated by Django 5.0.2 on 2024-03-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_category_news_news_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
